Repository gopinath-langote/1build, pull requests merged in 2019-09, with the labels that each got.

#137 Fix lint issues
  testing/def/definitions.go
  testing/fixtures/command_init_fixtures.go
  testing/fixtures/command_list_fixtures.go
  testing/fixtures/command_root_fixtures.go
  testing/fixtures/command_set_fixtures.go
  testing/fixtures/command_unset_fixtures.go
  testing/fixtures/execute_cmd_fixtures.go
  testing/fixtures/fixures.go
  testing/fixtures/flag_version_fixtures.go
  testing/utils/test_utils.go
Labels: documentation

#139 Fixes error message and formats command line output
  cmd/exec/exec.go
  cmd/models/onebuild-execution-plan.go
  cmd/root.go
  cmd/utils/utils.go
  docs/CHANGELOG.md
  go.mod
  go.sum
  testing/fixtures/command_init_fixtures.go
  testing/fixtures/execute_cmd_fixtures.go
Labels: In Progress, dependencies, enhancement

#148 Auto releaser
  ci-reporter.yml
Labels: enhancement

#151 Add contributors in release drafter
  .github/pull_request_template.md
  .github/release-drafter.yml
  docs/CHANGELOG.md
Labels: enhancement

#152 Release drafter
  .github/release-drafter.yml
  .github/workflows/release-management.yml
Labels: enhancement

#147 Implements functionality to unset multiple commands in one call
  README.md
  cmd/unset.go
  testing/fixtures/command_unset_fixtures.go
Labels: Hacktoberfest, In Progress, enhancement

#153 Fix typo errors
  cmd/exec/exec.go
  cmd/utils/utils.go
  testing/fixtures/execute_cmd_fixtures.go
Labels: enhancement

#157 Add phase banners to the tops of each phase
  cmd/exec/exec.go
  cmd/models/onebuild-execution-plan.go
  cmd/utils/utils.go
  testing/fixtures/execute_cmd_fixtures.go
Labels: Hacktoberfest, In Progress, new_feature
