Repository gopinath-langote/1build, pull requests merged in 2019-06, with the labels that each got.

#78 Upgrade ruamel.yaml to 0.15.97
  setup.py
Labels: enhancement

#76 Release 1.0.0
  docs/CHANGELOG.md
Labels: documentation

#80 Show version of `1build`
  README.md
  onebuild/__init__.py
  onebuild/input_parser.py
  onebuild/main.py
  onebuild/utils.py
  setup.py
  tests/test_help_command.py
  tests/test_version_command.py
Labels: enhancement, help wanted

#90 Add changelog draft
  docs/CHANGELOG.md
Labels: documentation, enhancement

#95 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#99 Travis CI use py3 for running tests on all os
  .travis.yml
  docs/CHANGELOG.md
Labels: CI/CD, test

#97 Add init command to create default config file
  docs/CHANGELOG.md
  onebuild/action_to_command_lookup.py
  onebuild/command.py
  onebuild/executor.py
  onebuild/file_writer.py
  onebuild/help_command.py
  onebuild/init_command.py
  onebuild/input_parser.py
  onebuild/list_command.py
  onebuild/main.py
  onebuild/perform_command.py
  onebuild/predefined_actions.py
  onebuild/utils.py
  onebuild/version_command.py
  requirements.txt
  tests/test_file_writer.py
  tests/test_help_command.py
  tests/test_init_command.py
Labels: In Progress, new feature

#104 Do not override `1build.yaml` if already exists in --init command
  README.md
  onebuild/init_command.py
  tests/test_init_command.py
Labels: bug

#106 Release 1.1.0
  docs/CHANGELOG.md
  onebuild/__init__.py
  tests/test_version_command.py
Labels: documentation, version-upgrade
