Repository gopinath-langote/1build, pull requests merged in 2019-10, with the labels that each got.

#160 Print total results banner at the end of execution
  cmd/exec/exec.go
  cmd/utils/printer.go
  testing/fixtures/execute_cmd_fixtures.go
Labels: Hacktoberfest, In Progress, new_feature

#164 Pretty print exec results
  cmd/config/parse.go
  cmd/exec/exec.go
  cmd/models/onebuild-execution-plan.go
  cmd/utils/printer.go
  cmd/utils/utils.go
  testing/cli_test.go
  testing/fixtures/execute_cmd_fixtures.go
  testing/utils/test_utils.go
Labels: Hacktoberfest, enhancement

#174 add Homebrew installation instruction to README
  README.md
Labels: needs-more-info

#163 1build project setup in 1build config
  1build.yaml
Labels: Hacktoberfest, Team Discussion

#168 Added delete config file command
  cmd/config/io.go
  cmd/delete.go
  testing/fixtures/command_delete_fixtures.go
  testing/fixtures/fixures.go
Labels: Hacktoberfest, In Progress, new_feature

#175 Set/Unset Before/After steps
  README.md
  cmd/config/parse.go
  cmd/set.go
  cmd/unset.go
  testing/fixtures/command_set_fixtures.go
  testing/fixtures/command_unset_fixtures.go
Labels: Hacktoberfest, enhancement
